# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

[package]
name = "apache-beam-runner-tests"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "Integration tests for Apache Beam Rust SDK transforms that require a runner to execute"
publish = false

[lib]
name = "tests"

[[bin]]
name = "beam-runner-tests-worker"
path = "src/worker.rs"

[[bin]]
name = "beam-runner-tests-expansion-service"
path = "src/expansion_service.rs"

[dependencies]
beam = { workspace = true, features = ["fluent", "io-file", "gcs", "derive", "external", "prism", "dataflow", "testing", "parquet", "avro"] }
prism = { workspace = true }
file = { workspace = true }
gcp = { workspace = true }
fluent = { workspace = true }
external = { workspace = true }
expansion = { workspace = true }
clap = { workspace = true }
inventory = { workspace = true }
prost = { workspace = true }
serde = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
model = { workspace = true }
tonic = { workspace = true }

[lints]
workspace = true

